<?php
/**
 * @file
 * Code for the UUID Menu Links Pages feature.
 */

include_once 'uuid_menu_links_pages.features.inc';

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 */
function uuid_menu_links_pages_form_menu_edit_item_alter(&$form, &$form_state, $form_id) {
  if (!empty($form['link_path'])) {
    $form['link_path']['#description'] .= '<br />' . t('You can also use UUID for node and taxonomy term urls. ie. node/CONTENT_UUID and taxonomy/term/TERM_UUID.');
    $form['link_path']['#description'] .= ' ' . t('See <a href="@uuid_content_page">UUID content list page</a> and <a href="@uuid_taxonomy_page">UUID taxonomy list page</a> to find the UUID for given entities.', array('@uuid_content_page' => url('admin/content/content-uuid'), '@uuid_taxonomy_page' => url('admin/structure/taxonomy/taxonomy_uuid')));
  }
}